name: CI - Lint, Test, and Push

on: [push, pull_request]

jobs:
  lint-test-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose version

      - name: Lint with Ruff
        run: docker compose run --rm test hatch run lint
        continue-on-error: true

      - name: Run tests
        run: docker compose run --rm test
        continue-on-error: true

      - name: Get short Git SHA
        id: vars
        run: |
          echo "timestamp=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT
          echo "branch=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-')" >> $GITHUB_OUTPUT

        
      - name:  Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image with tags
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/simple-rest-db:latest \
                       -t ${{ secrets.DOCKER_USERNAME }}/simple-rest-db:${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.timestamp }} \
                       .

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/simple-rest-db:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/simple-rest-db:${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.timestamp }}